### ISSUE TITLE
Nginx Proxy manager configs?

### ISSUE THREAD

**Issue by MilkMGN** [Wikidepia/InstaFix#166]
Hey,

Wanting to deploy ddinsta on my lab. Would you know how to deploy this if i am not behind Trafik, and instead behind Nginx Proxy Manager? I assume i am missing some options as the docker-compose container is not printing anything in the log. 

I assume it's just `<yourdomain>/reel/<id>`? 

Thanks

**Comment by starikh** [comment]
Just add instafix container to same docker network as your nginx-proxy-manager.

Then create simple proxy host 

![Image](https://github.com/user-attachments/assets/00add5ca-ffa3-448d-a473-0d704ddcb193)

For example my docker-compose config:

```
services:
  instafix:
    container_name: isfix
    image: ghcr.io/wikidepia/instafix:main
    restart: unless-stopped
    #ports:
    #  - "3000:3000"
    networks:
      -  npm-srv-1
networks:
  npm-srv-1:
     external: true
```
