### ISSUE TITLE
A docker version of the service can't find binary `instafix` on running

### ISSUE THREAD

**Issue by ghost** [Wikidepia/InstaFix#77]
```
[zelgray@zelgray scripts]$ docker compose up
[+] Running 2/1
 ✔ Network scripts_default       Created                                                                                                                                                                                                                                           0.3s
 ✔ Container scripts-instafix-1  Created                                                                                                                                                                                                                                           0.0s
Attaching to instafix-1
instafix-1  | exec /instafix: no such file or directory
instafix-1 exited with code 1
instafix-1  | exec /instafix: no such file or directory
instafix-1  | exec /instafix: no such file or directory
instafix-1 exited with code 1
```

**Comment by d3lac** [comment]
I see the same error,

`exec /instafix: no such file or directory`

**Comment by UlyssesZh** [comment]
Same error. My compose file:
```yml
services:
  instafix:
    container_name: instafix
    image: ghcr.io/wikidepia/instafix:main
    restart: unless-stopped
    ports:
      - "127.0.0.1:3003:3000"
```
